on:
  push:
    branches: [ main ]
    
jobs:
  List-Repos:
    runs-on: ubuntu-latest
    name: Job para listar repositórios de um usuário
    steps:
    - name: List Repos
      uses: geovanams/action-list-repos-msbuild@main
      with:
        user: geovanams
